# This is a basic workflow to help you get started with Actions

name: ci

on:
  push:
    branches: [ release/* ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: set golang
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/checkout@v2
      - name: Run a multi-line script
        run: |
          make build-release
          echo ::set-env name=tarname::$TARNAME
          echo ::set-env name=version::$VERSION
          echo ::set-env name=tarabs::$TARABS
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.version }}
          release_name: v${{ env.version }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.tarabs }}
          asset_name: ${{ env.tarname }}
          asset_content_type: application/octet-stream